# Generated by Django 3.2.6 on 2021-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hobby',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
