# Generated by Django 3.2.6 on 2021-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_author_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hometown',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
